// <auto-generated />
namespace ghumpo.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedImageType_ImageListingMapper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedImageType_ImageListingMapper));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101140391_AddedImageType_ImageListingMapper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
