// <auto-generated />
namespace ghumpo.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_businessgrouptable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_businessgrouptable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703171913442_added_businessgrouptable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
